<a href="https://colab.research.google.com/github/Helllcat/NumPy/blob/main/image_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from skimage.io import imread #image read inth format of array

from skimage.transform import resize

import os

import pandas as pd

In [ ]:
os.listdir("/content/drive/MyDrive/archive (14)")

['dogs_set', 'cats_set']

In [ ]:
len(os.listdir("/content/drive/MyDrive/archive (14)/cats_set"))

500

In [ ]:
len(os.listdir("/content/drive/MyDrive/archive (14)/dogs_set"))

512

In [ ]:
p=os.path.join("/content/drive/MyDrive/archive (14)","cats_set")

In [ ]:
for i in os.listdir(p):
  print(i)

cat.4080.jpg
cat.4079.jpg
cat.4107.jpg
cat.4075.jpg
cat.4076.jpg
cat.4108.jpg
cat.4086.jpg
cat.4089.jpg
cat.4096.jpg
cat.4097.jpg
cat.4116.jpg
cat.4088.jpg
cat.4082.jpg
cat.4103.jpg
cat.4090.jpg
cat.4077.jpg
cat.4094.jpg
cat.4084.jpg
cat.4085.jpg
cat.4102.jpg
cat.4093.jpg
cat.4095.jpg
cat.4106.jpg
cat.4113.jpg
cat.4098.jpg
cat.4081.jpg
cat.4111.jpg
cat.4078.jpg
cat.4100.jpg
cat.4101.jpg
cat.4092.jpg
cat.4099.jpg
cat.4109.jpg
cat.4112.jpg
cat.4087.jpg
cat.4114.jpg
cat.4091.jpg
cat.4083.jpg
cat.4104.jpg
cat.4105.jpg
cat.4110.jpg
cat.4115.jpg
cat.4126.jpg
cat.4158.jpg
cat.4118.jpg
cat.4119.jpg
cat.4139.jpg
cat.4150.jpg
cat.4164.jpg
cat.4151.jpg
cat.4154.jpg
cat.4160.jpg
cat.4152.jpg
cat.4143.jpg
cat.4165.jpg
cat.4127.jpg
cat.4142.jpg
cat.4125.jpg
cat.4144.jpg
cat.4166.jpg
cat.4128.jpg
cat.4159.jpg
cat.4122.jpg
cat.4133.jpg
cat.4161.jpg
cat.4163.jpg
cat.4135.jpg
cat.4153.jpg
cat.4155.jpg
cat.4137.jpg
cat.4120.jpg
cat.4117.jpg
cat.4162.jpg
cat.4121.jpg
cat.4124.jpg
cat.4148.jpg
cat.4132.jpg

In [ ]:
flat_data=[]
target=[]
catagories=["cats_set","dogs_set"]

file_path="/content/drive/MyDrive/archive (14)"

for i in catagories:
  print("loading>>>>>",i)
  path=os.path.join(file_path,i)

  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))
    img_resize=resize(img_array,(150,150,3))
    flat_data.append(img_resize.flatten())
    target.append(catagories.index(i))
  print('loaded')

loading>>>>> cats_set
loaded
loading>>>>> dogs_set
loaded


In [ ]:
df=pd.DataFrame(flat_data)

df.head()

0         1         2         3         4         5         6      \
0  0.677120  0.630061  0.645748  0.682750  0.635691  0.651377  0.686156   
1  0.890301  0.858125  0.789899  0.893206  0.867407  0.796021  0.886935   
2  0.676523  0.680445  0.700053  0.690212  0.694133  0.713741  0.703098   
3  0.504177  0.312776  0.085513  0.541762  0.383625  0.145249  0.554867   
4  0.368007  0.411136  0.426826  0.382182  0.425311  0.441001  0.196635   

      7         8         9      ...     67490     67491     67492     67493  \
0  0.639097  0.654784  0.697966  ...  0.668465  0.418038  0.371245  0.341417   
1  0.871940  0.797532  0.883740  ...  0.524630  0.642771  0.579384  0.516639   
2  0.707020  0.726628  0.724013  ...  0.677422  0.674967  0.674954  0.682837   
3  0.427365  0.178475  0.592912  ...  0.275703  0.577187  0.467383  0.277440   
4  0.239765  0.255455  0.455813  ...  0.107782  0.036107  0.051789  0.061279   

      67494     67495     67496     67497     67498     67499  
0  0.139135  0.104279  0.125323  0.575739  0.476284  0.491827  
1  0.641169  0.577227  0.514482  0.637624  0.571670  0.508925  
2  0.685937  0.685780  0.694094  0.697281  0.694175  0.711335  
3  0.572136  0.462332  0.276923  0.570475  0.460672  0.267800  
4  0.055380  0.072107  0.065898  0.078253  0.097756  0.082385  

[5 rows x 67500 columns]

In [ ]:
print(target)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
x=df
y=pd.DataFrame(target)

In [ ]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

x=ss.fit_transform(x)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42, test_size=.2)

from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

sv1=SVC(kernel='linear')

sv2=SVC(kernel='poly')

sv3=SVC(kernel='rbf')

l=[sv1, sv2, sv3]

for i in l:
  i.fit(x_train,y_train)
  y_predict=i.predict(x_test)
  print(accuracy_score(y_test,y_predict))
  print(confusion_matrix(y_test,y_predict))
  print(classification_report(y_test, y_predict))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.4876847290640394
[[53 45]
 [59 46]]
              precision    recall  f1-score   support

           0       0.47      0.54      0.50        98
           1       0.51      0.44      0.47       105

    accuracy                           0.49       203
   macro avg       0.49      0.49      0.49       203
weighted avg       0.49      0.49      0.49       203



/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5566502463054187
[[24 74]
 [16 89]]
              precision    recall  f1-score   support

           0       0.60      0.24      0.35        98
           1       0.55      0.85      0.66       105

    accuracy                           0.56       203
   macro avg       0.57      0.55      0.51       203
weighted avg       0.57      0.56      0.51       203



/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.541871921182266
[[53 45]
 [48 57]]
              precision    recall  f1-score   support

           0       0.52      0.54      0.53        98
           1       0.56      0.54      0.55       105

    accuracy                           0.54       203
   macro avg       0.54      0.54      0.54       203
weighted avg       0.54      0.54      0.54       203

