<a href="https://colab.research.google.com/github/Helllcat/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python
#array same colection of data with same datatype(homogenious)
a=np.array([1,2,3.1,4])
print(a)

[1.  2.  3.1 4. ]


In [ ]:
a=np.array([1,2,3.4,4,'a'])
a

array(['1', '2', '3.4', '4', 'a'], dtype='<U32')

In [ ]:
#slicing  foward and backward slicing
b=np.array([1,2,3,4,5])
print(b[0:2])
print(b[-1:-3:-1])
print(b[3:])
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension
import numpy as np
a=np.array([0,1,2,3,4,5])
c=np.array([[0,8],[1,2]])
print(a.ndim) #dimensiopn=1 vector
print(c.ndim)


1
2


In [ ]:

#create a 2x2 matrix 2,3,45
z=np.array([[2,3],[4,5]])
print(z)
print(z.shape)
print(z.ndim)
print(z.size)# size used for find total number of elements in amatrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
c=np.array([[2,3,4],[4,5,5]])
print(c)
print(c.size)
print(c.ndim)

[[2 3 4]
 [4 5 5]]
6
2


In [ ]:
#create a4x2 matrix
s=np.array([[4,5],[6,7],[2,3],[4,5]])
print(s)
print(s.shape)
print(s.ndim)
print(s.size)

[[4 5]
 [6 7]
 [2 3]
 [4 5]]
(4, 2)
2
8


In [ ]:
#create 4x4 matrix
import numpy as np

n=np.array([[1,2,3,4],[1,3,4,5],[3,4,5,6],[4,5,6,7]])
print(n)
n[0]

[[1 2 3 4]
 [1 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


array([1, 2, 3, 4])

19/09/2025

In [ ]:
print(n[0])

print(n[:,0])

print(n[1,1])

print(n[2,2])

print(n[3,2:])

print(n[2:,2:])

print(n[2:,1:3])

[1 2 3 4]
[1 1 3 4]
3
5
[6 7]
[[5 6]
 [6 7]]
[[4 5]
 [5 6]]


23/09/2025