<a href="https://colab.research.google.com/github/Helllcat/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python
#array same colection of data with same datatype(homogenious)
a=np.array([1,2,3.1,4])
print(a)

[1.  2.  3.1 4. ]


In [ ]:
a=np.array([1,2,3.4,4,'a'])
a

array(['1', '2', '3.4', '4', 'a'], dtype='<U32')

In [ ]:
#slicing  foward and backward slicing
b=np.array([1,2,3,4,5])
print(b[0:2])
print(b[-1:-3:-1])
print(b[3:])
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension
import numpy as np
a=np.array([0,1,2,3,4,5])
c=np.array([[0,8],[1,2]])
print(a.ndim) #dimensiopn=1 vector
print(c.ndim)


1
2


In [ ]:

#create a 2x2 matrix 2,3,45
z=np.array([[2,3],[4,5]])
print(z)
print(z.shape)
print(z.ndim)
print(z.size)# size used for find total number of elements in amatrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
c=np.array([[2,3,4],[4,5,5]])
print(c)
print(c.size)
print(c.ndim)

[[2 3 4]
 [4 5 5]]
6
2


In [ ]:
#create a4x2 matrix
s=np.array([[4,5],[6,7],[2,3],[4,5]])
print(s)
print(s.shape)
print(s.ndim)
print(s.size)

[[4 5]
 [6 7]
 [2 3]
 [4 5]]
(4, 2)
2
8


In [ ]:
#create 4x4 matrix
import numpy as np

n=np.array([[1,2,3,4],[1,3,4,5],[3,4,5,6],[4,5,6,7]])
print(n)
n[0]

[[1 2 3 4]
 [1 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


array([1, 2, 3, 4])

19/09/2025

In [ ]:
print(n[0])

print(n[:,0])

print(n[1,1])

print(n[2,2])

print(n[3,2:])

print(n[2:,2:])

print(n[2:,1:3])

[1 2 3 4]
[1 1 3 4]
3
5
[6 7]
[[5 6]
 [6 7]]
[[4 5]
 [5 6]]


In [6]:
import numpy as np
#zero metrix
z=np.zeros([3,3,3],dtype=int)
n=np.zeros([3,3,3],dtype=complex)
z
n

array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [9]:
#one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
#create 2x2 matrix

a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [11]:
#matrix addition
print(a+b)

[[ 4  6]
 [ 8 10]]


In [12]:
#matrix substraction
print(a-b)

[[-2 -2]
 [-2 -2]]


In [15]:
#matrix multiplication

print(a*b)  #not a matrix multiplication
print(a@b)  # the way to multiply the matrix
#another way of matrix multiplication
print(a.dot(b))

[[ 3  8]
 [15 24]]
[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


In [17]:
#matrix division
print(a/b)


[[0.33333333 0.5       ]
 [0.6        0.66666667]]


In [19]:
#full matrix

z=np.full([3,3],7,dtype=int)
z

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
#create a 3x4 matrix value 9 and data type complex
z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [27]:
#identity matrix
#the square matrix which has one as element

z=np.identity(3,dtype=int)
x=np.eye(3,dtype=int)
print(x)
print(z)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [31]:
#create 4x4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [37]:
#re shaping
a=y.reshape(8,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [39]:
#arrange
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [40]:
#create a 5x2 matrix arange
z=np.arange(1,11).reshape(5,2)
print(z)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [41]:
#create a 3x3 matrix with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])


array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [42]:
#floor
z=np.floor(a)
print(z)

[[2. 3. 3.]
 [1. 1. 6.]
 [7. 2. 7.]]


In [44]:
#ceil
z=np.ceil(a)
print(z)

[[3. 4. 4.]
 [2. 2. 7.]
 [8. 3. 8.]]


In [45]:
#round
z=np.round(a)
z======

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [54]:
#create 3x3 matrix
a=np.arange(1,10).reshape(3,3)
print(a)
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.min())
print(a.min(axis=1))
print(a.min(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[3 6 9]
[7 8 9]
1
[1 4 7]
[1 2 3]


23/09/2025